# Pretty much only doing one thing
# TODO robadams@illinois.edu add tests
# TODO automate release, including generate a patch file.
stages:
  - compile

compile_deb:
  tags: ["docker"]
  stage: compile
  image: illinoisrobert/kernel-build
  script:
    # Some people like tarballs; some like debs. We'll build both
    # Note: "make O=o" is not compatible with "deb-pkg", so we won't use it.
    - make  defconfig rob.config memorizer.config
    - make -j $(expr $(nproc) / 3 + 1) deb-pkg
    # I don't know why deb-pkg puts the files where we can't reach them.
    - mv ../linux-* .
  artifacts:
    expire_in: 1 week
    paths:
      - ./.config
      - ./vmlinux
      - ./linux-*

compile_tar:
  tags: ["docker"]
  stage: compile
  image: illinoisrobert/kernel-build
  script:
    # Some people like tarballs; some like debs. We'll build both
    # Note: "make O=o" is not compatible with "deb-pkg", so we won't use it.
    - make  defconfig rob.config memorizer.config
    - make -j $(expr $(nproc) / 3 + 1) tar-pkg
  artifacts:
    expire_in: 1 week
    paths:
      - .config
      - vmlinux
      - ./*.tar
