--- arch/x86/purgatory/Makefile
+++ arch/x86/purgatory/Makefile
@@ -37,6 +37,7 @@ UBSAN_SANITIZE	:= n
 KCSAN_SANITIZE	:= n
 KMSAN_SANITIZE	:= n
 KCOV_INSTRUMENT := n
+MEMORIZER_INSTRUMENT := n
 
 # These are adjustments to the compiler flags used for objects that
 # make up the standalone purgatory.ro
@@ -66,6 +67,10 @@ ifdef CONFIG_RETPOLINE
 PURGATORY_CFLAGS_REMOVE		+= $(RETPOLINE_CFLAGS)
 endif
 
+ifdef CONFIG_MEMORIZER
+PURGATORY_CFLAGS_REMOVE		+= -finstrument-functions
+endif
+
 ifdef CONFIG_CFI_CLANG
 PURGATORY_CFLAGS_REMOVE		+= $(CC_FLAGS_CFI)
 endif
