--- arch/x86/ia32/Makefile
+++ arch/x86/ia32/Makefile
@@ -3,6 +3,11 @@
 # Makefile for the ia32 kernel emulation subsystem.
 #
 
+MEMORIZER_INSTRUMENT_ia32_signal.o := n
+ifdef CONFIG_MEMORIZER
+KASAN_SANITIZE_ia32_signal.o := n
+endif
+
 obj-$(CONFIG_IA32_EMULATION) := ia32_signal.o
 
 audit-class-$(CONFIG_AUDIT) := audit.o
